# Generated by Django 4.1.1 on 2025-11-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('price_usd', models.FloatField()),
                ('volume_24h', models.FloatField()),
                ('market_cap', models.FloatField()),
                ('percent_change_1h', models.FloatField()),
                ('percent_change_24h', models.FloatField()),
                ('percent_change_7d', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
