# Generated by Django 4.1.1 on 2025-12-11 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cryptoprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coingecko_id', models.CharField(max_length=100, unique=True)),
                ('symbol', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_usd', models.DecimalField(decimal_places=8, max_digits=25)),
                ('volume_24h', models.DecimalField(decimal_places=2, max_digits=30)),
                ('market_cap', models.DecimalField(decimal_places=2, max_digits=30)),
                ('price_change_percentage_1h', models.FloatField(null=True)),
                ('price_change_percentage_24h', models.FloatField(null=True)),
                ('price_change_percentage_7d', models.FloatField(null=True)),
                ('timestamp', models.DateTimeField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='core.asset')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='CryptoPrice',
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['asset', 'timestamp'], name='core_priceh_asset_i_916c24_idx'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['timestamp'], name='core_priceh_timesta_0e4fd1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pricehistory',
            unique_together={('asset', 'timestamp')},
        ),
    ]
